// ============================================================================
// EFVM PÁTIO 360 — Domain Events
// Event Sourcing: Todos os eventos são imutáveis e formam a trilha de auditoria
// ============================================================================

import type { UUID, ISODateTime, Matricula, DeviceFingerprint } from '../contracts';

// ── Base Event ──────────────────────────────────────────────────────────

/** Metadados comuns a todos os domain events */
export interface DomainEventMetadata {
  /** UUID v4 do evento (idempotency key) */
  readonly eventId: UUID;
  /** ID do aggregate afetado */
  readonly aggregateId: UUID;
  /** Tipo do aggregate */
  readonly aggregateType: 'ServicePass' | 'YardConfiguration' | 'LocomotiveInspection';
  /** Tipo do evento */
  readonly eventType: string;
  /** Versão do aggregate após este evento */
  readonly version: number;
  /** Timestamp do evento (device clock) */
  readonly timestamp: ISODateTime;
  /** Matrícula do operador que gerou o evento */
  readonly operatorMatricula: Matricula;
  /** Device fingerprint */
  readonly deviceId: DeviceFingerprint;
  /** ID do pátio (contexto) */
  readonly yardId?: string;
}

/** Base interface para todos os domain events */
export interface DomainEvent<T = unknown> extends DomainEventMetadata {
  /** Payload específico do evento */
  readonly payload: T;
}

// ── ServicePass Events ──────────────────────────────────────────────────

export interface ServicePassCreatedPayload {
  shiftDate: string;
  shiftLetter: string;
  shiftWindow: string;
  yardId: string;
  yardName: string;
  dssReference: string;
}

export interface YardSnapshotRecordedPayload {
  upperTracks: Array<{ trackId: string; status: string; trainPrefix: string; wagonCount: string }>;
  lowerTracks: Array<{ trackId: string; status: string; trainPrefix: string; wagonCount: string }>;
  switches: Array<{ switchId: string; position: string; observation: string }>;
  equipment: Array<{ name: string; operational: boolean; observation: string }>;
  upperInspection: { type: string; observation: string };
  lowerInspection: { type: string; observation: string };
}

export interface TrainStatusRecordedPayload {
  linkEstablished: boolean;
  leakTestPassed: boolean;
  gradientTestPassed: boolean;
  atcConfigured: boolean;
  totalWeight: number;
  heaviestWagon: number;
  lightestWagon: number;
  excessDetected: boolean;
  aspirationDone: boolean;
  psiApplied: number;
  interleavedWagons: boolean;
}

export interface WeighingCompletedPayload {
  totalWeight: number;
  heaviestWagonId: string;
  heaviestWagonWeight: number;
  lightestWagonId: string;
  lightestWagonWeight: number;
  wagonCount: number;
  excessDetected: boolean;
  excessWagons: Array<{ wagonId: string; weight: number; excess: number }>;
}

export interface WeighingExcessDetectedPayload {
  wagonId: string;
  weight: number;
  limit: number;
  excess: number;
  recommendedAction: 'recuo_alivio_repesagem' | 'atualizacao_manual';
}

export interface LocomotiveInspectionStartedPayload {
  locomotiveId: string;
  locomotiveModel: string;
  origin: string;
  hoursStopped: number;
  triggerReason: 'origin' | 'model' | 'hours_stopped' | 'manual';
}

export interface LocomotiveInspectionCompletedPayload {
  items: Array<{
    itemId: string;
    name: string;
    status: 'ok' | 'nok' | 'na';
    observation: string;
  }>;
  helpDeskCalled: boolean;
  interventionRequired: boolean;
  overallResult: 'approved' | 'conditional' | 'rejected';
}

export interface SafetyAssessmentRecordedPayload {
  criticalShunting: boolean;
  shuntingType: string;
  shuntingLocation: string;
  brakesVerified: boolean;
  criticalPoint: boolean;
  criticalPointDescription: string;
  trackClear: boolean;
  communicationCompleted: boolean;
  activeRestriction: boolean;
  restrictionType: string;
  restrictionLocation: string;
}

export interface AlertGeneratedPayload {
  alertType: string;
  severity: 'critico' | 'aviso' | 'info';
  section: string;
  message: string;
  field?: string;
  recommendedAction?: string;
  autoGenerated: boolean;
}

export interface AlertAcknowledgedPayload {
  alertId: UUID;
  acknowledgment: string;
}

export interface AnomalyRegisteredPayload {
  anomalyType: string;
  description: string;
  location: string;
  severity: 'baixa' | 'media' | 'alta' | 'critica';
  equipmentId?: string;
  normativeRef?: string;
}

export interface ServicePassSignedPayload {
  signatureType: 'outgoing' | 'incoming';
  operatorName: string;
  operatorMatricula: Matricula;
  formIntegrityHash: string;
  signedAt: ISODateTime;
}

export interface ServicePassSealedPayload {
  outgoingHash: string;
  incomingHash: string;
  sealTimestamp: ISODateTime;
  totalFormHash: string;
}

export interface ServicePassSyncedPayload {
  syncTimestamp: ISODateTime;
  serverVersion: number;
  conflictsResolved: number;
}

export interface ConflictDetectedPayload {
  localVersion: number;
  serverVersion: number;
  conflictFields: string[];
  detectedAt: ISODateTime;
}

export interface ConflictResolvedPayload {
  resolution: 'local' | 'server' | 'manual';
  resolvedBy: Matricula;
  mergedFields: string[];
}

// ── Event Payload Map (typed access for projections/use-cases) ──────────

/** Maps event type strings to their typed payloads */
export interface EventPayloadMap {
  ServicePassCreated: ServicePassCreatedPayload;
  YardSnapshotRecorded: YardSnapshotRecordedPayload;
  TrainStatusRecorded: TrainStatusRecordedPayload;
  WeighingCompleted: WeighingCompletedPayload;
  WeighingExcessDetected: WeighingExcessDetectedPayload;
  LocomotiveInspectionStarted: LocomotiveInspectionStartedPayload;
  LocomotiveInspectionCompleted: LocomotiveInspectionCompletedPayload;
  SafetyAssessmentRecorded: SafetyAssessmentRecordedPayload;
  AlertGenerated: AlertGeneratedPayload;
  AlertAcknowledged: AlertAcknowledgedPayload;
  AnomalyRegistered: AnomalyRegisteredPayload;
  ServicePassSigned: ServicePassSignedPayload;
  ServicePassSealed: ServicePassSealedPayload;
  ServicePassSynced: ServicePassSyncedPayload;
  ConflictDetected: ConflictDetectedPayload;
  ConflictResolved: ConflictResolvedPayload;
}

/** Helper type: extract typed payload from a DomainEvent by eventType */
export type TypedPayload<T extends keyof EventPayloadMap> = EventPayloadMap[T];

// ── Event Type Constants ────────────────────────────────────────────────

export const EVENT_TYPES = {
  // ServicePass lifecycle
  SERVICE_PASS_CREATED: 'ServicePassCreated',
  YARD_SNAPSHOT_RECORDED: 'YardSnapshotRecorded',
  TRAIN_STATUS_RECORDED: 'TrainStatusRecorded',
  WEIGHING_COMPLETED: 'WeighingCompleted',
  WEIGHING_EXCESS_DETECTED: 'WeighingExcessDetected',
  LOCOMOTIVE_INSPECTION_STARTED: 'LocomotiveInspectionStarted',
  LOCOMOTIVE_INSPECTION_COMPLETED: 'LocomotiveInspectionCompleted',
  SAFETY_ASSESSMENT_RECORDED: 'SafetyAssessmentRecorded',
  ALERT_GENERATED: 'AlertGenerated',
  ALERT_ACKNOWLEDGED: 'AlertAcknowledged',
  ANOMALY_REGISTERED: 'AnomalyRegistered',
  SERVICE_PASS_SIGNED: 'ServicePassSigned',
  SERVICE_PASS_SEALED: 'ServicePassSealed',
  SERVICE_PASS_SYNCED: 'ServicePassSynced',
  CONFLICT_DETECTED: 'ConflictDetected',
  CONFLICT_RESOLVED: 'ConflictResolved',
} as const;

export type EventType = typeof EVENT_TYPES[keyof typeof EVENT_TYPES];

// ── Event Factory ───────────────────────────────────────────────────────

let eventVersion = 0;

export function createDomainEvent<T>(
  eventType: EventType,
  aggregateId: UUID,
  aggregateType: DomainEventMetadata['aggregateType'],
  payload: T,
  operatorMatricula: Matricula,
  deviceId: DeviceFingerprint,
  yardId?: string,
): DomainEvent<T> {
  eventVersion++;
  return Object.freeze({
    eventId: crypto.randomUUID(),
    aggregateId,
    aggregateType,
    eventType,
    version: eventVersion,
    timestamp: new Date().toISOString(),
    operatorMatricula,
    deviceId,
    yardId,
    payload,
  });
}
