import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const args = new Set(process.argv.slice(2));
const writeMode = args.has('--write');
const checkMode = args.has('--check');

const markdownTargets = [
  'README.md',
  'DEPLOY.md',
  'CONTRIBUTING.md',
  'CHANGELOG.md',
  ...walk('docs').filter(file => file.endsWith('.md')),
];

const facts = {
  workspacePackages: readWorkspacePackages(),
  workflows: listRelativeFiles('.github/workflows', '.yml'),
  docs: listRelativeFiles('docs', '.md'),
  frontend: {
    pages: countDirectories('frontend/src/pages'),
    hooks: countCodeFiles('frontend/src/hooks'),
    components: countCodeFiles('frontend/src/components'),
    domainAggregates: countCodeFiles('frontend/src/domain/aggregates'),
    tests: countCodeFiles('frontend/__tests__'),
  },
  backend: {
    controllers: countCodeFiles('backend/src/controllers'),
    models: countCodeFiles('backend/src/models'),
    middleware: countCodeFiles('backend/src/middleware'),
    services: countCodeFiles('backend/src/services'),
    migrations: countCodeFiles('backend/src/migrations'),
    tests: countCodeFiles('backend/__tests__'),
  },
  quality: {
    e2eSpecs: countCodeFiles('e2e/specs'),
    loadTests: listRelativeFiles('load-tests/scenarios', '.js').length,
  },
};

const generated = renderFactsMarkdown(facts);
const factsPath = path.join(root, 'docs', 'REPOSITORY_FACTS.md');

if (writeMode) {
  fs.writeFileSync(factsPath, generated);
}

const linkErrors = validateMarkdownLinks(markdownTargets);
const factErrors = [];

if (checkMode && fs.existsSync(factsPath)) {
  const existing = fs.readFileSync(factsPath, 'utf8');
  if (existing !== generated) {
    factErrors.push('docs/REPOSITORY_FACTS.md is stale. Run `pnpm facts`.');
  }
}

const errors = [...factErrors, ...linkErrors];

if (writeMode && !checkMode) {
  console.log(`Updated ${path.relative(root, factsPath)}`);
}

if (errors.length > 0) {
  for (const error of errors) console.error(error);
  process.exit(1);
}

if (checkMode) {
  console.log('Repository facts and local markdown links are valid.');
}

function walk(relativeDir) {
  const base = path.join(root, relativeDir);
  if (!fs.existsSync(base)) return [];
  const results = [];
  for (const entry of fs.readdirSync(base, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name === 'dist' || entry.name === '.git') continue;
    const rel = path.join(relativeDir, entry.name);
    const full = path.join(root, rel);
    if (entry.isDirectory()) {
      results.push(...walk(rel));
      continue;
    }
    results.push(rel);
  }
  return results.sort();
}

function listRelativeFiles(relativeDir, suffix) {
  return walk(relativeDir).filter(file => file.endsWith(suffix));
}

function countDirectories(relativeDir) {
  const full = path.join(root, relativeDir);
  if (!fs.existsSync(full)) return 0;
  return fs.readdirSync(full, { withFileTypes: true }).filter(entry => entry.isDirectory()).length;
}

function countCodeFiles(relativeDir) {
  return walk(relativeDir).filter(file => /\.(ts|tsx)$/.test(file)).length;
}

function readWorkspacePackages() {
  const content = fs.readFileSync(path.join(root, 'pnpm-workspace.yaml'), 'utf8');
  return content
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.startsWith('- '))
    .map(line => line.replace(/^-\s*['"]?/, '').replace(/['"]?$/, ''));
}

function renderFactsMarkdown(data) {
  return `# Repository Facts

This file is generated by \`pnpm facts\`. Do not edit manually.

## Workspace

- Package manager: \`pnpm@10.30.1\`
- Workspace packages: ${data.workspacePackages.map(pkg => `\`${pkg}\``).join(', ')}
- CI/CD workflows: ${data.workflows.length}
- Documentation files under \`docs/\`: ${data.docs.length}

## Frontend

| Metric | Count |
| --- | ---: |
| Page directories under \`frontend/src/pages\` | ${data.frontend.pages} |
| Hook files under \`frontend/src/hooks\` | ${data.frontend.hooks} |
| Component files under \`frontend/src/components\` | ${data.frontend.components} |
| Aggregate files under \`frontend/src/domain/aggregates\` | ${data.frontend.domainAggregates} |
| Test files under \`frontend/__tests__\` | ${data.frontend.tests} |

## Backend

| Metric | Count |
| --- | ---: |
| Controller files under \`backend/src/controllers\` | ${data.backend.controllers} |
| Model files under \`backend/src/models\` | ${data.backend.models} |
| Middleware files under \`backend/src/middleware\` | ${data.backend.middleware} |
| Service files under \`backend/src/services\` | ${data.backend.services} |
| Migration files under \`backend/src/migrations\` | ${data.backend.migrations} |
| Test files under \`backend/__tests__\` | ${data.backend.tests} |

## Quality Surface

| Metric | Count |
| --- | ---: |
| Playwright specs under \`e2e/specs\` | ${data.quality.e2eSpecs} |
| k6 scenarios under \`load-tests/scenarios\` | ${data.quality.loadTests} |

## Workflows

${data.workflows.map(file => `- \`${file}\``).join('\n')}
`;
}

function validateMarkdownLinks(files) {
  const errors = [];
  const linkPattern = /\[[^\]]*]\(([^)]+)\)/g;

  for (const file of files) {
    const content = fs.readFileSync(path.join(root, file), 'utf8');
    for (const match of content.matchAll(linkPattern)) {
      const target = match[1].trim();
      if (!target || target.startsWith('http://') || target.startsWith('https://') || target.startsWith('mailto:') || target.startsWith('#')) continue;
      const cleanTarget = target.split('#')[0];
      if (!cleanTarget) continue;
      const resolved = path.resolve(path.dirname(path.join(root, file)), cleanTarget);
      if (!fs.existsSync(resolved)) {
        errors.push(`${file}: missing linked file ${target}`);
      }
    }
  }

  return errors;
}
